spring.application.name=ticketingsystem

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ticsystemDB
spring.datasource.username=postgres
spring.datasource.password=Tejasmanu1819

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# JWT
jwt.secret=wsdcvbnjkuyhgfdsfghjklo9iuyhgfdrtyuiop-poikjuhygtqdfagvbznmkdijuhnxm-ddndjdhbhdxjxjxxnn
jwt.expiration=86400000